dist: bionic
language: python
python:
  - "3.6"
install:
  - pip install .
  - pip install pytest==6.1.1 pytest-pylint==0.17.0 moto==1.3.16 coverage==5.3 codecov==2.1.9 tqdm
script:
  - coverage run -m pytest
  - coverage report
  - coverage xml
after_success:
  - codecov
